
server:
  port: 8081

spring:
  datasource:
    url: jdbc:h2:mem:api
    username: sa
    password:
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    org:  
      hibernate:
        SQL: debug